### ISSUE TITLE
关于滤波电容问题

### ISSUE THREAD

**Issue by yamiyamiiiiiiiii** [1452206376/ESP8266_BADUSB#2]
请问您在readme里提到的需要添加滤波电容问题，在立创平台内的原理图及pcb图修改了吗，因为我看到里面是有一个电容的，所以不太明白是否已修改

**Comment by ghost** [comment]
当时自己蚀刻的PCB，空间不够就没画。  
最好是加一个，防止电流过大，ESP8266重启
